name: Verify Conditions
description: Verify a few things needed in our workflows before proceeding
outputs:
  should-build:
    description: Tells EAS workflows if they should build binaries or not
    value: ${{ contains(steps.changed-files.outputs.modified_files, 'bun.lockb') }}
  check-deps-integrity:
    description: Tells workflows if dependency checks should be done
    value: ${{ contains(steps.changed-files.outputs.modified_files, 'bun.lockb') }}

runs:
  using: 'composite'

  steps:
    - name: 🗃️ Verify changed files
      uses: tj-actions/changed-files@v45
      id: changed-files
      with:
        files: |
          package.json
          bun.lockb
          .github/**/*.yml
